### ISSUE TITLE
When compiling: explints.hpp: No such file or directory

### ISSUE THREAD

**Issue by Charsy89** [nagalun/worldofpixels-server#4]
Title. ConnectionManager.hpp line 10 references it but it doesn't exist.
![image](https://user-images.githubusercontent.com/28523197/71773163-4f54d600-2f15-11ea-8786-93a7d5bab4ef.png)

**Comment by nagalun** [comment]
You might need to fetch the submodules first.
```
git submodule init
git submodule update
```

**Comment by Charsy89** [comment]
That appears to have worked, but now there's another reference error:
`./lib/uWebSockets/src/Networking.h:7:10: fatal error: openssl/opensslv.h: No such file or directory`
I think it's part of uWebSockets though. Should I go open an issue on their repo?

**Comment by nagalun** [comment]
you need uwebsocket's dependencies (build deps) installed for it to compile. on debian based distros i think the packages are called libssl-dev and zlib1-dev

**Comment by nagalun** [comment]
by the way, if you're compiling the latest server version, it will be useless to you since the old client doesn't work for it.
you need to revert to this commit https://github.com/nagalun/worldofpixels-server/commit/8c27537c0d0c620bee5d24463b46fd177d6bef8a

**Comment by Charsy89** [comment]
Installing libssl-dev worked. zlib1-dev was obseleted but zlib1g-dev appeared to work.
Yet another error though: `src/ProxyChecker.cpp:5:10: fatal error: keys.hpp: No such file or directory` (even after reverting to the older commit)

**Comment by Charsy89** [comment]
Ok so NOW i reverted to the mentioned commit. Same error though, just in Server.cpp.

**Comment by Charsy89** [comment]
Okay so i figured out that i have to create keys.hpp myself. I did that (left it empty) and now it needs `NOTHING_SPECIAL_JUST_IGNORE_THIS_LINE_OF_TEXT_KTHX` and `CAPTCHA_API_KEY` declared. I've never read or written c++ code before, so may i ask how to define those :<

**Comment by nagalun** [comment]
remove special line and replace captcha api with ""
